### ISSUE TITLE
Clarify equals()

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-ri#63]
See https://github.com/unitsofmeasurement/uom-se/issues/158 but for https://github.com/unitsofmeasurement/unit-ri/issues/62

Plus refining primitive comparison so only compatible types like "floating point" or "integer" ones get compared in a resource-effective manner.

**Comment by keilw** [comment]
@otaviojava type checking between A and B is already applied, so would you be able to provide a reasonable number of test cases for various types?

**Comment by otaviojava** [comment]
That still not working on uom-se: https://github.com/unitsofmeasurement/uom-se/blob/master/src/main/java/tec/uom/se/AbstractQuantity.java#L440

Yes, a huge number is test is really important, mainly because lost precision is complicated

**Comment by keilw** [comment]
No because it's a separate issue ;-)
