### ISSUE TITLE
Consider a new name for a (future) RI

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-ri#67]
Given most JSRs have more or less fancy and "divine" code names for Reference Implementations like
- Moneta (JSR 354)
- Soteria (JSR 375)
- Diana / Artemis (Eclipse JNoSQL, not a JSR yet)
I wanted to raise the question of a code name for this RI if the JSR progresses (likely with a new number)

Two mythological names both related to senses or measurement are:
-  [Indriya](https://en.wikipedia.org/wiki/Indriya) -   the Sanskrit and Pali term for physical strength or ability in general, and for the senses more specifically
- [Thoth or Djehuti](https://en.wikipedia.org/wiki/Thoth) - Ancient Egyptian God of Knowledge, the Moon, Measurement, Wisdom,...
- [Seshat](https://en.wikipedia.org/wiki/Seshat)  - Companion/daughter of [Thoth](https://en.wikipedia.org/wiki/Thoth)

**Comment by keilw** [comment]
As a personal note, I find **Indriya** a bit easier to pronounce. **Thoth** may also be "somewhat" OK, while **Djehuti** (or Jehuti which would be an appealing tweak for the Java community) unfortunately may sound a bit like "jihadi" and you certainly would not like to have anything near that word (I doubt any serious Java project exists under such name;-)

**Comment by keilw** [comment]
Having Nespresso offer an Indian coffee [Indriya](https://www.nespresso.com/au/en/order/capsules/indriya-from-india-coffee-capsule) makes its case even more compelling. Like other flavors e.g. "Lungo" the name is a basic term from a country or language, so there are no branding issues, as long as we don't call a project "Nespresso" or "Nestle" ;-) Having Indriya associated with coffee sounds perfect for a Java project.

**Comment by dautelle** [comment]
Seshat -  [https://en.wikipedia.org/wiki/Seshat]

**Comment by keilw** [comment]
Thanks, will add the option to the list. I was aware since Seshat is a companion of Thoth in Egyptian mythology. 
@dautelle Does hat also mean a +1 from your side for this choice?

**Comment by dautelle** [comment]
Good idea to having Nespresso capsule name for Java code :)

**Comment by keilw** [comment]
So is that a +1 for Indriya then?;-)

**Comment by keilw** [comment]
IC you left +1 for both. No problem, they'll all be counted in the end.

**Comment by keilw** [comment]
We have a **winner**. The final result is: 
- 4 votes for **Indriya**
- 1 vote for Sheshat
