### ISSUE TITLE
`ParserException(CharSequence parsedData, int position)` is used with an error message

### ISSUE THREAD

**Issue by Woodz** [unitsofmeasurement/unit-ri#68]
`public ParserException(String message, CharSequence parsedData, int position)` should be the constructor used when there is an error message as this stores the error message in the exception message. Currently, we are getting unhelpful messages like `javax.measure.format.ParserException: Parse Error` which do not contain any useful message.

**Comment by keilw** [comment]
It depends on where this kind of error happens. ParserException is used in different situations and characters or the exact parsing exception are not always available. Maybe in future splitting it into more than one exception for parsing/formatting might help. Could you provide an exact situation or JUnit test to reproduce what you're facing?

**Comment by Woodz** [comment]
@keilw I will isolate a reproducible test case and identify the source of this exception to see if it can be augmented with a more useful error message

**Comment by Woodz** [comment]
So the issue was from `SimpleUnitFormat.getInstance().parse("CM")` which caused the exception to be thrown at https://github.com/unitsofmeasurement/unit-ri/blob/master/src/main/java/tec/units/ri/format/SimpleUnitFormat.java#L577. However, looking at the inputs to the method, there is more context available. Are you happy for me to raise a PR?

**Comment by keilw** [comment]
If you need to format this exact string, please have a look at `UCUMFormat` in https://github.com/unitsofmeasurement/uom-systems which allows case-insensitive parsing. Are you a JCP member? Ideally for PRs to the RI one should at least be an Associate Member of the JCP.

**Comment by Woodz** [comment]
I am not a JCP member, but surely the community can offer bug fixes in RI with sufficient review?

**Comment by keilw** [comment]
In many cases the JCP/PMO is a bit strict. What affects the Java SE port more is an Eclipse Contributor License (because that is used by several projects and commercial products derived from) but the RI is a little less problematic. Because of strains of OpenJDK Eclipse projects won't use it, so I will check it out and merge if everything looks good.
