### ISSUE TITLE
Small fix: Transformed units symbol

### ISSUE THREAD

**Issue by solanvp** [unitsofmeasurement/unit-ri#74]
Hi

When working with alternate unites like Feet, Fahrenheit and so on, a  custom symbol can be used, but in the TransformedUnit constructor, the symbol is being ignored: 

```
  public TransformedUnit(String symbol, Unit<Q> parentUnit, UnitConverter unitConverter) {
    this(null, parentUnit, parentUnit.getSystemUnit(), unitConverter);
  }
```

A simple change would really help out:
```
  public TransformedUnit(String symbol, Unit<Q> parentUnit, UnitConverter unitConverter) {
    this(symbol, parentUnit, parentUnit.getSystemUnit(), unitConverter);
  }
```

Thanks and regards

**Comment by keilw** [comment]
Please use the label() method of SimpleUnitFormat instead, in most cases TransformedUnit has no symbol by design, that doesn't mean the unit cannot have a label/visual representation.
